manifest:
  projects:
    - name: zmk
      url: https://github.com/zmkfirmware/zmk
      revision: 9ebbeff0a8b69a42f14aec022cdf16c7a107b9e0
      import: app/west.yml
    - name: zephyr
      url: https://github.com/zmkfirmware/zephyr
      revision: 10ba6d0cb38bc3d258775d27982f707599320085
      import:
        name-allowlist: [cmsis, hal_espressif, hal_xtensa, picolibc]
  self:
    path: pixel-pro
